/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.bbk.concurreport.options;

import java.util.prefs.Preferences;
import org.openide.util.NbPreferences;

public final class ConCurReportOptionsPanel extends javax.swing.JPanel {
    
    private final ConCurReportOptionsOptionsPanelController controller;
    
    ConCurReportOptionsPanel(ConCurReportOptionsOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup = new javax.swing.ButtonGroup();
        buttonOneHTML = new javax.swing.JRadioButton();
        buttonHTMLforEach = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridBagLayout());

        buttonGroup.add(buttonOneHTML);
        org.openide.awt.Mnemonics.setLocalizedText(buttonOneHTML, org.openide.util.NbBundle.getMessage(ConCurReportOptionsPanel.class, "ConCurReportOptionsPanel.buttonOneHTML.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.ipady = 153;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(buttonOneHTML, gridBagConstraints);

        buttonGroup.add(buttonHTMLforEach);
        org.openide.awt.Mnemonics.setLocalizedText(buttonHTMLforEach, org.openide.util.NbBundle.getMessage(ConCurReportOptionsPanel.class, "ConCurReportOptionsPanel.buttonHTMLforEach.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.ipady = 153;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(buttonHTMLforEach, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        Preferences preferences = NbPreferences.forModule(ConCurReportOptionsPanel.class);
        boolean oneHTML = preferences.getBoolean(JUST_ONE_HTML, true);
        buttonOneHTML.setSelected(oneHTML);
        buttonHTMLforEach.setSelected(!oneHTML);
    }
    
    void store() {
        Preferences preferences = NbPreferences.forModule(ConCurReportOptionsPanel.class);
        boolean oneHTML = buttonOneHTML.isSelected();
        preferences.putBoolean(JUST_ONE_HTML, oneHTML);       
    }
    
    public static final String JUST_ONE_HTML = "oneHTML";
    
    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton buttonHTMLforEach;
    private javax.swing.JRadioButton buttonOneHTML;
    // End of variables declaration//GEN-END:variables
}
